# Generated by Django 4.2.13 on 2024-06-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('faculty', models.CharField(max_length=100)),
                ('gpa', models.FloatField()),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
