# Generated by Django 4.2.13 on 2024-06-12 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='canteen',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='students.canteen'),
            preserve_default=False,
        ),
    ]
