# Generated by Django 4.2.13 on 2024-06-12 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_canteen_dish_canteen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='canteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='students.canteen'),
        ),
    ]
