# Generated by Django 4.2.13 on 2024-06-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_dish_canteen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='canteen',
        ),
        migrations.DeleteModel(
            name='Canteen',
        ),
    ]
